routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

//route resource
Route::resource('/posts', \App\Http\Controllers\PostController::class);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    
    /**
     * fillable
     *
     * @var array
     */
    protected $fillable = ['nama', 'nik', 'tgl_lahir', 'tmp_lahir', 'photo', 'alamat'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{    
    public function index()
    {
        $posts = Post::latest()->paginate(5);
        return view('penduduk.index', compact('posts'));
    }
    
    public function create()
    {
        return view('penduduk.create');
    }
    
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama'      => 'required',
            'nik'       => 'required|max:16',
            'tgl_lahir' => 'required',
            'tmp_lahir' => 'required',
            'photo'     => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'alamat'    => 'required'
        ]);

        $photo = $request->file('photo');
        $photo->storeAs('public/image', $photo->hashName());

        Post::create([
            'nama'     => $request->nama,
            'nik'   => $request->nik,
            'tgl_lahir' => $request->tgl_lahir,
            'tmp_lahir' => $request->tmp_lahir,
            'photo'     => $photo->hashName(),
            'alamat' => $request->alamat,
        ]);
        return redirect()->route('posts.index')->with(['success' => 'Data Berhasil Disimpan!']);
    }

    public function edit(Post $post)
    {
        return view('penduduk.edit', compact('post'));
    }

    public function update(Request $request, Post $post){

        // $this->validate($request, [
        //     'nama'      => 'required',
        //     'nik'       => 'required|max:16',
        //     'tgl_lahir' => 'required',
        //     'tmp_lahir' => 'required',
        //     'photo'     => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        //     'alamat'    => 'required'
        // ]);

        if($request->hasFile('photo')){
            $photo = $request->file('photo');
            $photo->storeAs('public/image', $photo->hashName());
            Storage::delete('public/image/'.$post->photo);
            $post->update([
                'nama'      => $request->nama,
                'nik'       => $request->nik,
                'tgl_lahir' => $request->tgl_lahir,
                'tmp_lahir' => $request->tmp_lahir,
                'photo'     => $photo->hashName(),
                'alamat'     => $request->alamat,
            ]);
        }else{
            $post->update([
                'nama'     => $request->nama,
                'nik'   => $request->nik,
                'tgl_lahir' => $request->tgl_lahir,
                'tmp_lahir' => $request->tmp_lahir,
                'alamat' => $request->alamat,
            ]);
        }
        return redirect()->route('posts.index')->with(['success' => 'Data Berhasil Diubah!']);

    }
    public function destroy(Post $post)
    {
        Storage::delete('public/posts/'. $post->image);
        $post->delete();
        return redirect()->route('posts.index')->with(['success' => 'Data Berhasil Dihapus!']);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>ADMIN</title>

    @include('partials/css')

</head>

<body class="theme-blue theme-blue-light">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="preloader">
                <div class="spinner-layer pl-red">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>Harap tunggu...</p>
        </div>
    </div>
    <!-- #END# Page Loader -->
    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>
    <!-- #END# Overlay For Sidebars -->

    <!-- Top Bar -->
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <!-- <img src="{{ asset('img/log.png') }}" alt="" width="45px" class="pull-right"> -->
                <a href="javascript:void(0);" class="bars"></a>
                <a class="navbar-brand" href="#">Ruang Admin</a>
            </div>
        </div>
    </nav>
    <!-- #Top Bar -->
    <section>
        <!-- Left Sidebar -->
        <aside id="leftsidebar" class="sidebar">
            <!-- User Info -->
            <div class="user-info">
                <br><br>
                <div class="info-container">
                    <div data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin</div>
                    <div class="email">Selamat Datang, Admin</div>
                    <div class="btn-group user-helper-dropdown">
                        <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    <i class=" material-icons">input</i>Keluar</a>
                            </li>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- #User Info -->
            <!-- Menu -->
            <div class="menu">
                <ul class="list">
                    <li class="header">DASHBOARD</li>
                    <li class="@yield('#')">
                        <a href="#">
                            <i class="material-icons">dashboard</i>
                            <span>Dashboard</span>
                        </a>
                    </li>

                    <li class="header">MASTER DATA</li>
                    <!-- <li class="@yield('#')">
                        <a href="#">
                            <i class="material-icons">book</i>
                            <span>Permintaan</span>
                        </a>
                    </li> -->
                    <li class="@yield('#')">
                        <a href="#">
                            <i class="material-icons">settings</i>
                            <span>Setting</span>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- #Menu -->
            <!-- Footer -->
            <div class="legal">
                <div class="copyright">
                    <!-- Nothing here.. -->
                </div>
                <div class="version">
                    Admin <b>v 1.0</b>
                </div>
            </div>
            <!-- #Footer -->
        </aside>
        <!-- #END# Left Sidebar -->
    </section>

    <section class="content">
        @yield('content')
    </section>

    @yield('js')

    @include('partials/js')

</body>

</html>

resources/views/partials/css.blade.php
    <!-- Favicon-->
    <link rel="icon" href="favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="{{ asset('bsb/plugins/bootstrap/css/bootstrap.css') }}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{ asset('bsb/plugins/node-waves/waves.css') }}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ asset('bsb/plugins/animate-css/animate.css') }}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{{ asset('bsb/css/style.css') }}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="{{ asset('bsb/css/themes/all-themes.css') }}" rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link href="{{ asset('bsb/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet">

    <!-- Bootstrap Select Css -->
    <link href="{{ asset('bsb/plugins/bootstrap-select/css/bootstrap-select.css') }}" rel="stylesheet">

resources/views/partials/js.blade.php
    <!-- Jquery Core Js -->
    <script src="{{ asset('bsb/plugins/jquery/jquery.min.js') }}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{{ asset('bsb/plugins/bootstrap/js/bootstrap.js') }}"></script>

    <!-- Select Plugin Js -->
    <script src="{{ asset('bsb/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{{ asset('bsb/plugins/jquery-slimscroll/jquery.slimscroll.js') }}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{{ asset('bsb/plugins/node-waves/waves.js') }}"></script>

    <!-- Jquery CountTo Plugin Js -->
    <script src="{{ asset('bsb/plugins/jquery-countto/jquery.countTo.js') }}"></script>

    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('bsb/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('bsb/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script>
        var t = $('#table').DataTable({
            responsive: true,
            "lengthChange": false,
            "order": [
                [5, "desc"]
            ],
            "columnDefs": [{
                "orderable": false,
                "targets": [
                    0,
                    6
                ],
            }]
        });

        t.on('order.dt search.dt', function() {
            t.column(0, {
                search: 'applied',
                order: 'applied'
            }).nodes().each(function(cell, i) {
                cell.innerHTML = i + 1;
            });
        }).draw();
    </script>

    <!-- Custom Js -->
    <script src="{{ asset('bsb/js/admin.js') }}"></script>
    <script src="{{ asset('bsb/js/pages/index.js') }}"></script>

    <!-- Demo Js -->
    <script src="{{ asset('bsb/js/demo.js') }}"></script>

resources/views/penduduk/create.blade.php
@extends('layouts/app')
@section('dashboard', 'active')
@section('content')

<div class="container-fluid">
    <!-- <div class="block-header">
        <h2>DASHBOARD</h2>
    </div> -->
    

    <div class="row clearfix">
        <div class="col-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Tambah Data Penduduk
                    </h2>
                </div>

                <br>


                <div class="body">
                    <div class="row clearfix">
                        <div class="col-sm-12">
                            <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
                            
                            @csrf
                                <div class="form-group">
                                    <div class="form-line">
                                        <h2 class="card-inside-title">Photo</h2>
                                        <input type="file" class="form-control @error('photo') is-invalid @enderror" name="photo">
                                        @error('photo')
                                            <div class="alert alert-danger mt-2">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="form-line">
                                        <h2 class="card-inside-title">Nama</h2>
                                        <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{ old('nama') }}" placeholder="Masukkan Nama">
                                        @error('nama')
                                            <div class="alert alert-danger mt-2">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="form-line">
                                        <h2 class="card-inside-title">Nik</h2>
                                        <input type="text" class="form-control @error('nik') is-invalid @enderror" name="nik" value="{{ old('nik') }}" placeholder="Masukkan Nik">
                                        @error('nik')
                                            <div class="alert alert-danger mt-2">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="form-line">
                                        <h2 class="card-inside-title">Tempat Lahir</h2>
                                        <input type="text" class="form-control @error('tmp_lahir') is-invalid @enderror" name="tmp_lahir" value="{{ old('tmp_lahir') }}" placeholder="Masukkan tempat lahir">
                                    
                                        @error('tmp_lahir')
                                        <div class="alert alert-danger mt-2">
                                            {{ $message }}
                                        </div>
                                        @enderror
                                        </div>
                                </div>
                                <div class="form-group">
                                    <div class="form-line">
                                        <h2 class="card-inside-title">Tanggal Lahir</h2>
                                        <input type="date" class="form-control @error('tgl_lahir') is-invalid @enderror" name="tgl_lahir" value="{{ old('tgl_lahir') }}" placeholder="Masukkan tanggal lahir">
                                
                                        @error('tgl_lahir')
                                            <div class="alert alert-danger mt-2">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="form-line">
                                        <h2 class="card-inside-title">Alamat</h2>
                                        <textarea class="form-control @error('alamat') is-invalid @enderror" name="alamat" rows="5" placeholder="Masukkan Alamat">{{ old('alamat') }}</textarea>
                        
                                        @error('alamat')
                                            <div class="alert alert-danger mt-2">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-md btn-primary">SIMPAN</button>
                                <button type="reset" class="btn btn-md btn-warning">RESET</button>

                            </form>
                        </div>
                    </div>
               
                      
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/penduduk/edit.blade.php
@extends('layouts/app')
@section('dashboard', 'active')
@section('content')

<div class="container-fluid">
    <div class="row clearfix">
        <div class="col-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Edit Data Penduduk
                    </h2>
                </div>

                <br>


                <div class="body">
                    <div class="row clearfix">
                        <div class="col-sm-12">
                       
                            <form action="{{ route('posts.update', $post->id) }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group">
                                    <div class="form-line">
                                        <h2 class="card-inside-title">Photo</h2>
                                        <input type="file" class="form-control" name="photo">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="form-line">
                                        <h2 class="card-inside-title">Nama</h2>
                                        <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{ old('nama', $post->nama) }}" placeholder="Masukkan Nama">
                            
                            @error('nama')
                                <div class="alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                            @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="form-line">
                                        <h2 class="card-inside-title">Nik</h2>
                                        <input type="text" class="form-control @error('nik') is-invalid @enderror" name="nik" value="{{ old('nik', $post->nik) }}" placeholder="Masukkan Nik">
                            
                                @error('nik')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="form-line">
                                        <h2 class="card-inside-title">Tempat Lahir</h2>
                                        <input type="text" class="form-control @error('tmp_lahir') is-invalid @enderror" name="tmp_lahir" value="{{ old('tmp_lahir', $post->tmp_lahir) }}" placeholder="Masukkan tempat lahir">
                                        
                                        @error('tmp_lahir')
                                        <div class="alert alert-danger mt-2">
                                            {{ $message }}
                                        </div>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="form-line">
                                        <h2 class="card-inside-title">Tanggal Lahir</h2>
                                        <input type="date" class="form-control @error('tgl_lahir') is-invalid @enderror" name="tgl_lahir" value="{{ old('tgl_lahir', $post->tgl_lahir) }}" placeholder="Masukkan tanggal lahir">
                                    
                                    @error('tgl_lahir')
                                        <div class="alert alert-danger mt-2">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="form-line">
                                        <h2 class="card-inside-title">Alamat</h2>
                                        <textarea class="form-control @error('alamat') is-invalid @enderror" name="alamat" rows="5" placeholder="Masukkan Alamat">{{ old('alamat', $post->alamat) }}</textarea>
                                @error('alamat')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-md btn-primary">UPDATE</button>
                            <button type="reset" class="btn btn-md btn-warning">RESET</button>

                            </form>
                        </div>
                    </div>
               
                      
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/penduduk/index.blade.php
@extends('layouts/app')
@section('dashboard', 'active')
@section('content')

<div class="container-fluid">
    <div class="block-header">
        <h2>DASHBOARD</h2>
    </div>

    <div class="row clearfix">
        <div class="col-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Data Penduduk
                    </h2>
                </div>

                <br>

                <div class="container-fluid">
                    <div class="pull-right">
                        <a href="{{ route('posts.create') }}" class="btn btn-md btn-success waves-effect">TAMBAH</a>
                    </div>
                </div>

                <div class="body">
                    <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Photo</th>
                                <th scope="col">Nama</th>
                                <th scope="col">Nik</th>
                                <th scope="col">Tanggal Lahir</th>
                                <th scope="col">Tempat Lahir</th>
                                <th scope="col">Alamat</th>
                                <th scope="col">AKSI</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($posts as $post)
                            <tr>
                                <td class="text-center">
                                    <img src="{{ Storage::url('public/image/').$post->photo }}" class="rounded" style="width: 150px">
                                </td>
                                <td>{{ $post->nama }}</td>
                                <td>{{ $post->nik }}</td>
                                <td>{{ $post->tgl_lahir }}</td>
                                <td>{{ $post->tmp_lahir }}</td>
                                <td>{!! $post->alamat !!}</td>
                                <td class="text-center">
                                    <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('posts.destroy', $post->id) }}" method="POST">
                                        <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-sm btn-primary">EDIT</a>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-danger">HAPUS</button>
                                    </form>
                                </td>
                            </tr>
                            @empty
                            <div class="alert alert-danger">
                                Data Post belum Tersedia.
                            </div>
                            @endforelse
                        </tbody>
                    </table>  
                    {{ $posts->links() }}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('js')
<script>
        @if(session()->has('success'))
        
            toastr.success('{{ session('success') }}', 'BERHASIL!'); 

        @elseif(session()->has('error'))

            toastr.error('{{ session('error') }}', 'GAGAL!'); 
            
        @endif
    </script>
@endsection